# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: updater.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'updater.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupdater.proto\"&\n\x12GetVersionsRequest\x12\x10\n\x08show_all\x18\x01 \x01(\x08\"\xc1\x01\n\x0bVersionInfo\x12\x10\n\x08\x64ir_name\x18\x01 \x01(\t\x12\x11\n\tbuild_tag\x18\x02 \x01(\t\x12\x15\n\rbuild_version\x18\x03 \x01(\t\x12\x18\n\x10git_release_hash\x18\x04 \x01(\t\x12\x17\n\x0fgit_release_tag\x18\x05 \x01(\t\x12\x1c\n\x14git_release_datetime\x18\x06 \x01(\t\x12\x12\n\ngit_branch\x18\x07 \x01(\t\x12\x11\n\tis_latest\x18\x08 \x01(\x08\"5\n\x13GetVersionsResponse\x12\x1e\n\x08versions\x18\x01 \x03(\x0b\x32\x0c.VersionInfo\")\n\rUpdateRequest\x12\x18\n\x10selected_version\x18\x01 \x01(\t\"6\n\tUpdateLog\x12\x13\n\x0blog_message\x18\x01 \x01(\t\x12\x14\n\x0cis_completed\x18\x02 \x01(\x08\x32~\n\nUpdaterApp\x12\x41\n\x14GetAvailableVersions\x12\x13.GetVersionsRequest\x1a\x14.GetVersionsResponse\x12-\n\rPerformUpdate\x12\x0e.UpdateRequest\x1a\n.UpdateLog0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'updater_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETVERSIONSREQUEST']._serialized_start=17
  _globals['_GETVERSIONSREQUEST']._serialized_end=55
  _globals['_VERSIONINFO']._serialized_start=58
  _globals['_VERSIONINFO']._serialized_end=251
  _globals['_GETVERSIONSRESPONSE']._serialized_start=253
  _globals['_GETVERSIONSRESPONSE']._serialized_end=306
  _globals['_UPDATEREQUEST']._serialized_start=308
  _globals['_UPDATEREQUEST']._serialized_end=349
  _globals['_UPDATELOG']._serialized_start=351
  _globals['_UPDATELOG']._serialized_end=405
  _globals['_UPDATERAPP']._serialized_start=407
  _globals['_UPDATERAPP']._serialized_end=533
# @@protoc_insertion_point(module_scope)
