# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import updater_pb2 as updater__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in updater_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UpdaterAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableVersions = channel.unary_unary(
                '/UpdaterApp/GetAvailableVersions',
                request_serializer=updater__pb2.GetVersionsRequest.SerializeToString,
                response_deserializer=updater__pb2.GetVersionsResponse.FromString,
                _registered_method=True)
        self.PerformUpdate = channel.unary_stream(
                '/UpdaterApp/PerformUpdate',
                request_serializer=updater__pb2.UpdateRequest.SerializeToString,
                response_deserializer=updater__pb2.UpdateLog.FromString,
                _registered_method=True)


class UpdaterAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdaterAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableVersions,
                    request_deserializer=updater__pb2.GetVersionsRequest.FromString,
                    response_serializer=updater__pb2.GetVersionsResponse.SerializeToString,
            ),
            'PerformUpdate': grpc.unary_stream_rpc_method_handler(
                    servicer.PerformUpdate,
                    request_deserializer=updater__pb2.UpdateRequest.FromString,
                    response_serializer=updater__pb2.UpdateLog.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UpdaterApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UpdaterApp', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UpdaterApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UpdaterApp/GetAvailableVersions',
            updater__pb2.GetVersionsRequest.SerializeToString,
            updater__pb2.GetVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerformUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/UpdaterApp/PerformUpdate',
            updater__pb2.UpdateRequest.SerializeToString,
            updater__pb2.UpdateLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
